# shellcheck shell=sh
alias rnt='review.next txt'
alias rnw='review.next web'
alias rn='review.next'
alias rp='review.park'
alias ru='review.unpark'
alias rrna='review.record na'
alias rr='review.record l'
alias rb='tar zcvf "review-state.$(date +%Y-%m-%d.%H%M).tar.gz" review.state.*'
